version: "3"

services:
  sonarqube:
    image: sonarqube
    ports:
      - "9005:9005"
    expose:
      - '9005'
#    networks:
#      - sonarnet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://127.0.0.1:5432/rainbow_database
      - sonar.jdbc.username=admin
      - sonar.jdbc.password=admin
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

#networks:
#  sonarnet:
 #   driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions: